### ISSUE TITLE
Generated but not accepted transactions showing first in Recent Transactions

### ISSUE THREAD

**Issue by chadrickm** [PIVX-Project/PIVX#111]
Would be awesome all transactions were just ordered by date.

![image](https://cloud.githubusercontent.com/assets/1383231/25030276/ed68dcc8-2091-11e7-9e9a-a5e35234572a.png)

**Comment by chadrickm** [comment]
This is only after 2.1.7 update. Wasn't happening before this...

**Comment by Fuzzbawls** [comment]
Funny, I was looking at this just last night and thinking of changing the default sort key so this doesn't happen anymore.

A bit of explanation as to what is going on under the hood here: 
Transactions are sorted by their confirmation count first, and conflicted transactions end up in a higher position because of that.

**Comment by lekanovic** [comment]
I have had the same problem, two times since I upgraded to 2.1.7

**Comment by VS15** [comment]
Me too.

**Comment by Fuzzbawls** [comment]
This issue is closed and has already had a fix applied, which is currently available in the master branch, and will be included in the next release.
