### ISSUE TITLE
[RFC] Stop shipping 32-bit binaries.

### ISSUE THREAD

**Issue by furszy** [PIVX-Project/PIVX#1315]
Will be short.

We are currently shipping 32-bit binaries by default. I don't see a good reason for continue shipping them (Upstream already dropped support for windows one and it's close to stop shipping linux one too).
People will be able to build their own binaries, I just propose to not ship them by default.

Immediate pros: Less Travis timeouts and Gitian will be faster.

**Comment by random-zebra** [comment]
Agreed. :+1:

**Comment by Fuzzbawls** [comment]
I'm in full agreement that we should stop providing pre-compiled binaries for win32 and i686 linux.

The last Intel 32-bit desktop processor was released in 2007, and the last AMD 32-bit desktop processor was released in 2004.

There are still 32-bit x86 processors being made, though mostly for integrated/embedded systems that are unlikely to ever be used for crypto wallet purposes.

Note: I think we **SHOULD** still ship linux armhf binaries (32-bit ARM architecture), as there are still a number of semi-recent SOC based devices that use such processors and are otherwise fully capable of, and indeed used for, crypto wallet purposes.

**Comment by random-zebra** [comment]
Closed in #1324
