### ISSUE TITLE
[Wallet] Segmentation fault on masternode with --disablewallet

### ISSUE THREAD

**Issue by aaronm-cloudtek** [PIVX-Project/PIVX#158]
### Describe the issue
Executing pivxd with options like `masternode=1 disablewallet=1` causes a segmentation fault with no useful debug output.

#### If so, please list the steps to reproduce below:
1. Add `disablewallet=1` to otherwise valid masternode configuration.
2. Run pivxd.

### Expected behavior
Program should throw InitError with useful troubleshooting information for user.

### Actual behavior
Segmentation fault.

### What version of PIVX Core are you using?
Self-compiled master commit id 41fdeaa

### Machine specs:
- OS: Tested on Debian, CentOS, and Arch Linux

### Any extra information that might be useful in the debugging process.
See my PR for a proposed fix.

**Comment by Fuzzbawls** [comment]
After some further review, I think more time will be needed to formulate a proper fix for this. Your PR #159 is a fix that can be applied locally to circumvent the error, but the larger picture is that many aspects of the software are expecting the wallet to be enabled and don't have the proper protection around them.

**Comment by AaronM-Cloudtek** [comment]
Fair enough. I'd still really like to see documentation added for the `-staking` option, especially since it's enabled by default.

**Comment by Fuzzbawls** [comment]
ahh yeah, that is a separate issue, but will need to be done regardless

**Comment by Fuzzbawls** [comment]
Might be a good idea to add/change the parameter interaction during initialization to disable staking if the wallet is also disabled at runtime (compile-time no-wallet builds are currently not working, but consideration should also be made to assume such functionality will be restored)

Examples of the type of parameter interaction I'm talking about can be seen when processing the `-connect` parameter, which if set will disable `-dnsseed` and `-listen`

If you feel up to the task, just post here and/or open a new PR, otherwise I will probably be able to work on it next week (this goes for anyone else that may have interest in addressing the issue too)

**Comment by AaronM-Cloudtek** [comment]
ok sounds good, i will submit a new PR

**Comment by Fuzzbawls** [comment]
Closing now that #180 has been merged
