### ISSUE TITLE
Cannot install 4.1.0 on MacOS 10.13.6

### ISSUE THREAD

**Issue by joae1975** [PIVX-Project/PIVX#1613]
When I try to instal the program, I get this message.  

It happens every time I try to install it. 

![Screen Shot 2020-05-10 at 9 06 42 PM](https://user-images.githubusercontent.com/4007744/81515457-2e0c5800-9302-11ea-8316-80bfff708b07.png)

**Comment by jakimanboy** [comment]
The .dmg file itself is fine but afaik it's got something to do with the developer license which I believe our developers are waiting on Apple for to be able to notorize the apps again. 

As per our developer's advice, you can bypass the error message for now by opening a terminal and issuing the following command (assuming you dragged the app to the "Applications" folder, otherwise substitute whatever location it is at below): 

xattr -d com.apple.quarantine /Applications/PIVX-Qt.app
