### ISSUE TITLE
Cross compiling for macOS, complains the files are damaged.

### ISSUE THREAD

**Issue by albertocastillo2001** [PIVX-Project/PIVX#1680]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue
After cloning PIVX, building depends for "x86_64-apple-darwin14" using the Apple SDK 10.11, and then building PIVX for Mac, the produced binaries don't work in the Mac computer. Says they are damaged and I should move them to trash

#### If so, please list the steps to reproduce below:
1. Git cloned PIVX
2. did `cd depends`
3. Created SDKs folder under depends `mkdir -p SDKs`
4. Pasted "MacOSX10.11.sdk" into "SDKs" folder I have just created
5. Ran `make HOST=x86_64-apple-darwin14`
6. Went back to Pivx root doing `cd ..`
7. Ran `./autogen.sh`
8. Ran `./configure --prefix=$PWD/depends/x86_64-apple-darwin14`
9. Ran `make`

### Expected behavior
pivx binaries should work on the MacOS computer

### Actual behavior
Says the files are damaged and should move them to trash

### What version of PIVX Core are you using?
4.11 commit 47bf23a

### Machine specs:
- OS: Ubuntu 18.04

### Any extra information that might be useful in the debugging process.
Due to my lack of experience with MacOS I can't really give out any information. The binaries cross compile succesfully on the Linux server tho.
Never had any issues cross compiling for other platforms.

running `make deploy` to produce the DMG file produces the dmg file properly and I am able to install it on the Mac, but Pivx Core doesn't work.

Thank you.

**Comment by albertocastillo2001** [comment]
Hi. Would it be possible to help me? Thank you.

**Comment by Fuzzbawls** [comment]
This isn't an issue with the wallet's code nor the build process, but rather an issue with recent versions of macOS (Mojave and Catalina) requiring apps to be code-signed and, in the case of Catalina, notarized.

We codesign and notarize our release binaries to be compliant with Apple's requirements, but someone like yourself, who is doing a cross-compilation on your own, and who would not likely be able to codesign nor notarize a self-compiled binary, this, unfortunately, is the expected behavior.

You can circumvent the error by copying the `PIVX-Qt.app` to your `/Applications` directory, then opening up a terminal and issuing the following command:
```bash
xattr -d com.apple.quarantine /Applications/PIVX-Qt.app
```

Aside from that, you can also compile directly on your macOS machine by following the instructions in [doc/build-osx.md](https://github.com/PIVX-Project/PIVX/blob/master/doc/build-osx.md). Natively-compiled apps aren't subject to the code-signing nor notarization requirements.
