### ISSUE TITLE
[RFC] Budget proposals killing-no threshold

### ISSUE THREAD

**Issue by random-zebra** [PIVX-Project/PIVX#1852]
Currently, a proposal is completely removed from the map (and becomes invalid) whenever the "net NO" vote count ("no" votes minus "yes votes) is higher than 10% of the active masternodes (see the section that #1845 factors out into  `CBudgetProposal::IsHeavilyDownvoted`).

This poses a risk, as any entity controlling more than 10% of the active masternodes, can kill any proposal at will (if acting shortly after its submission) making it "disappear" so that other masternodes are not even able to see it and vote on it.

I'm not sure about the original reasons behind the implementation of this check.
I think that we should either outright remove it (leaving any, otherwise valid, proposal in the map for the whole voting cycle), or drastically raise the 10% threshold (making it harder for MNOs to collude in order to nuke proposals).

**Comment by snappysnap** [comment]
100% - a solution that does not bump the proposals out would be wonderful as we've seen/observed cases where proposals just disappear before the community really ever had a chance to engage with them.

 I'm curious if the design of this was to somehow prevent spamming the network (in a bizarre sort of checks and balances way, where if some nefarious actor wanted to say submit 1000 proposals (waste of funds really) in some sort of spam attack, the MN holders could "combat" that by rapidly downvoting those proposals, thus removing them. Seems odd, but I can't see another way to prevent that rogue scenario (other than the already "economic" barrier of a submission fee).

given the above thought process, I would be inclined to say raise the threshold to some higher limit.  Removing it does seem "simpler" however, the only pause I have is that "spam proposal" attack.  Again, I don't know what that would accomplish other than making that voting cycle a PITA

**Comment by random-zebra** [comment]
Yes, spam should be prevented with (dis)incentives only (as is the fee).
Besides, I think that paying the submission fee should buy the right to have the proposal visible for the whole voting period.
It's not fair to pay the same price as anyone else, and get the proposal killed by a minority of voters.
And finally, masternode owners can always change their mind (and their votes) before the finalization (e.g. if more details about the proposal are released during the voting period).

**Comment by snappysnap** [comment]
Nuke it danno.  Like the thought process and reasoning.

**Comment by Fuzzbawls** [comment]
If i recall correctly, one of the reasons this was initially implemented was to remove very long-running proposals that were consistently voted down (ie, the github pro proposal from 2017 that had like a 24-cycle lifetime, and was quickly seen as way too much to justify).

AFAIK, we currently don't have an upper limit in the number of cycles a proposal can be submitted for on a protocol level. I think it would be a good idea to implement a protocol-level upper limit on the maximum number of cycles for a proposal to be accepted (say, max 6 cycles would be double what we have been commonly operating on...max 4 cycles or even max 3 cycles would also work).

Doing this would prevent a non-passing proposal from lingering around for excessive cycles, and in reality; if a proposal fails to pass 3 months (cycles) in a row, it is unlikely that it will ever gain traction to the point of passing, and even if it did, i would be worried that the proposal creator would have moved on, or that the original price per cycle would no longer be representative of  the proposed work/service.

So, in conclusion: I do agree that the current behavior NEEDS to be changed, and we should not be arbitrarily removing proposals simply because they get voted down before they are allowed ample time for others to vote them up. But, I also believe that some protocol-level limitation on the maximum number of cycles allowed is also needed.

**Comment by snappysnap** [comment]
I like this concept.  Might raise discussions (not for any "current" implementation) around "types" of proposals. I know at one time we had discussed various "categories" of proposals (be they requesting funds from budget or not), etc.

I know one "type" of proposal now that is looking/has historically used a 12 month cycle window (the alliance proposal, example with Zenzo).  The scope of this is to have a longer term horizon for this.  Of course, there is no reason these could not be done quarterly, but the 12 month span for this type makes sense (imo).

An Upper threshold does make sense (As outlined above by @Fuzzbawls).  I know we typically put in for 3 month cycles....but would welcome more feedback around this).

I could see (down the road) types of proposals having different "max" cycle thresholds.

**Comment by random-zebra** [comment]
I do agree that we should put a protocol-enforced limit to the payment count, but that would be a (soft) fork. Better to wait for 5.0.

In the meantime we could work on one or two changes that have no consensus effect (since downvoted proposals never become part of finalized budgets):

- Raise the threshold to something like 30%.

- Make it so that a heavily downvoted proposal can only be removed *N* blocks after the collateral transaction's block. And make N a constant high enough to leave ample time for the MNOs to see/vote on the proposal (e.g. an entire budget cycle of 43200 blocks).

**Comment by NoobieDev12** [comment]
The amount of BS allowed to the trolls and bad actors in the current PIVX governance model (although inherited) is absolutely insane and has to be changed as soon as possible. I'm glad this issue is opened for discussion here because we have recently seen in real time bad actors taking the advantage of this, from every single aspect, vulnerability. Raising the threshold to at least 30% sounds reasonable. Also, even if it gets downvoted by 30% for whatever reason, let the proposal stay by the end of the first budget cycle in which the proposal was submitted, allowing all the MNOs enough time to make their vote in reasonable time frame. Completely removing the proposal from voting ability without allowing every masternode owner to put their vote should not be possible to happen.

If proposal finish up the entire voting cycle with more than 30% of no votes, it should be completely removed (killed).
