### ISSUE TITLE
[RFC] Changing block reward distribution in favor of bigger PIVX treasury

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#2623]
Current distribution per block: 3 PIV goes to Masternode, 2 PIV goes to Staker, 1 PIV goes to Treasury.

Proposed distribution per block: **2 PIV** goes to Masternode, 2 PIV goes to Staker, **2 PIV** goes to Treasury.

After having a very constructive discussion on PIVX Discord earlier today, here comes the RFC to make it all public in a single place.
Idea is to make the distribution per block equal for Masternodes, Stakers and Treasury with the **main purpose** of increasing the monthly treasury **without increasing the inflation rate**.

As of right now and for the past few years, Masternodes were receiving more rewards than Stakers. Although economic forces were in place, Masternodes were always getting more rewards for one reason or another. It can be that 10k PIV in USD amount is out of reach for an average investor, it can be a technical knowledge limitation of an average investor to setup a Masternode, or something else, doesn't matter because it isn't a main focus of this discussion anyways.

The discussion on Discord revealed that **many Masternode owners are strongly supporting the idea of block reward redistribution**, where 1 PIV that currently goes to Masternodes in the future goes towards the Treasury in order to allow more funds available for various proposals, with a special emphasis on stronger Marketing, which is a weakest point of PIVX since inception. Additional funds in treasury, especially for Marketing purposes are expected to significantly increse the price per PIV.
Furthermore, Masternode owners on Discord unanimously agreed for this idea and didn't show intention of shutting down their Masternodes even if the block reward for Masternodes drop from current 3 PIV to proposed 2 PIV per block. Also, Masternodes will still have an advantage of having voting rights compared to Stakers.

However, let's even assume there will be a huge Masternode number drop due to decreased block reward. At the time of writing this issue, there are 1725 active Masternodes in the PIVX network. Just a couple months ago, PIVX had around 1300 active Masternodes in the network and there were no issues in the network at all. So, even if ~425 Masternodes go offline, network will still stay strong just like it was before.

**Thumbs up this post if you agree with the idea shared above.**
All comments for further discussion are more than welcome.

**Comment by furszy** [comment]
There will be a radical change in terms of the Masternodes importance in the network and their specification requirements in v6.0. They will be the network backbone, having direct and major implications in the consensus protocol.
 
Used for deployments of new network upgrades, minimum protocol version signaling, enabling transactions and chain locks (preventing reorganizations), budget distribution, and more.. even probably the new DKG system can be used as random source beacon for a new hybrid proof of stake model (research pending for this last point).

Changing the distribution, without a proper study, only viewing the current tier two network state, can and most likely will end up making the tier two network pointless and placing the entire network at risk.

This discussion is more suited after v6.0, when the new specifications and requirements will be clear.

**Comment by yenachar** [comment]
The PIV committed to staking and masternodes tends to automatically rebalance. So my take on this change is that it removes 20% of overall rewards for holders (5 becomes 4 PIV) while doubling protocol-driven investment in PIVX itself (1 becomes 2 PIV). Personally, I like that tradeoff, especially in light of my strong feeling that PIVX would benefit from more investment in both core functionality and marketing/outreach.

My biggest concern is assuring prudent use of the new investment funds. Maybe this could be coupled in some way with policy changes that increase transparency and community involvement and debate?

**Comment by EricStanek** [comment]
Hey @furszy! 

I understand your points. But, I don't see anything wrong with having the discussion in parallel. Also, 'after v6.0' could be a long time, because not all the functionality you list will be ready when v6.0 releases. Why wait?

Let me ask this .... and I know this is a BIG ASSUMPTION ..... but it helps us non-devs wrap our heads around things.

Assuming you had already completed the study to change the reward distribution, and everything looked OK to proceed, is it a big amount of development effort to change from 1 PIV to 2 PIV for the Treasury and from 3 PIV to 2 PIV for MN rewards? I know this would be in code that we inherited from Dash, and that it has been refactored quite a bit already - but perhaps there are still some 'spaghetti' sections in there that cause work.

Thanks for your time!

**Comment by EricStanek** [comment]
> The PIV committed to staking and masternodes tends to automatically rebalance. So my take on this change is that it removes 20% of overall rewards for holders (5 becomes 4 PIV) while doubling protocol-driven investment in PIVX itself (1 becomes 2 PIV). Personally, I like that tradeoff, especially in light of my strong feeling that PIVX would benefit from more investment in both core functionality and marketing/outreach.
> 
> My biggest concern is assuring prudent use of the new investment funds. Maybe this could be coupled in some way with policy changes that increase transparency and community involvement and debate?

Totally agree it would be great to have increased transparency and community involvement, but those things can't be automated or forced by policy. Only the dynamics of multiple competing proposals can achieve this. Too often people fear competing and worry that there won't be enough funds for every proposal. That creates mediocre proposals, or worse yet 'money grabbing' proposals. Far better to have so many proposals, we KNOW many will not succeed in being funded.

**Comment by ambassador000** [comment]
I can understand the viewpoint that the proposed change might be too radical due to potential drop of 33.33% of the Masternodes. So, how about doing the significantly smaller change, but still significantly increased monthly budget. So, the new block reward distribution would be the following:

**2.5 PIV** to Masternode
**2 PIV** to Staker
**1.5 PIV** to Treasury

**Comment by jakimanboy** [comment]
I am in favor of 2:2:2 myself. I like the equal roundness of the number, and that it will significantly increase the project's capability to fund things for PIVX in PIV, backed by a mutual goal of its success. It basically is an extra community-wide donation effort to boost PIVX project's development and marketing capacity.

**Comment by jakimanboy** [comment]
> Changing the distribution, without a proper study, only viewing the current tier two network state, can and most likely will end up making the tier two network pointless and placing the entire network at risk.
> 
> This discussion is more suited after v6.0, when the new specifications and requirements will be clear.

We probably will never have proper study performed. and tbh, none of the previous reward distribution ratio had much study either. Simply going by the success of other projects for the past many years of crypto, it can be said with certainty that higher inflation is actually good for the project, not worse. Simply put, we need to move faster and be more dynamic to adapt to the state of the project and the market. Giving larger portion of the block reward to the existing hodlers doesn't benefit the project. A project that has more money to spend on itself, in order to be able to increase its reach and value in the market is going to be more successful.

**Comment by SprefiX** [comment]
I agree with Jakimanboy as he said, the past clearly showed something else. I think that the network would not become unstable. Yes, some masternodes would disappear, but if you calculated that 33% of the masternodes would go offline, over 1150 nodes would still be active and secure the network well enough.
I am in favor of distributing 2: 2: 2 pivx per block. Yes, it will lower the annual return of the staker and masternode holder, but the whole point that metter is to achieve above-average marketing with the extra funds and push the Price, ( the Attention to new people in the market). When the marketing starts to work, we will be way ahead of the competition because we have a big fixed monthly budget for marketing.

**Comment by furszy** [comment]
First things first, let's not turn this technical RFC GitHub issue into a forum or a twitter talk.

No technical person will be convinced by random thoughts that favor one or the other side without understanding the network security implications that the incentive scheme modification proposed could have.

Briefly explained for everyone, the reason behind the higher incentives for running a MN comes from the facts that they are the network backbone, 24/7 online full nodes that store the complete blockchain, providing services to a larger extent of peers, fulfilling an expensive Proof of Service in order to prove that they are behaving properly, with higher specs requirements that any other actor in the network. 

The higher "rewards" as you label them aren't just payments to favor an elite class that does nothing for the network. There is a technical purpose, it encourages a certain type of actor in the network which provides higher network stability, services and security than any other actor.
Based on the Incentives Theory, individuals are presented with different choices and they act to maximize their expected utility, helping the network in the way.

And this is not just the initial point. I invite everyone that is willing to discuss this properly to read DIP3, DIP6, DIP7 and, for the future, DIP8. As they are where v6.0.0 is heading in order to solidify the tier two network and provide deep security implications to the tier one blockchain consensus protocol.

I have read some statements out there saying that the network will behave correctly with less than 100 MNs as well.. and that is completely false as the Long Live Masternodes Quorums minimum size is 400 and the network requires at least 3 to 4 times that number in order to not centralize and be able to complete the DKG protocol, and the LLMQ requests and signing sessions.

So, once more, this is not a simple topic, requires a study before introduce any modification as it not only affects the budget to get a marketing funding increment, (which, being direct, it has zero technical relevance in this topic) nor can be done only because you like round numbers. It's a topic that will affect the overall network stability and security if it's not done properly.

I'm not against studying the subject, but I'm definitely a NACK for any person/comment throwing random numbers and values like this would be PIVX from 2016/2017. No mor technically unsustained decisions that sooner or later end up hurting the network deeply, exploding and leaving problems for years.

**Comment by jakimanboy** [comment]
> I have read some statements out there saying that the network will behave correctly with less than 100 MNs as well.. and that is completely false as the Long Live Masternodes Quorums minimum size is 400 and the network requires at least 3 to 4 times that number in order to not centralize and be able to complete the DKG protocol, and the LLMQ requests and signing sessions

At the time when DASH activated LLMQ back in 2019, they had a masternode count of over 4800. Similar for FIRO (aka Zcoin back then) when they activated it last year. However, PIVX currently only has 1700 with frequent fluctuations to sub-1300, and even below 1000 few times a year. Also, our highest MN count was 2300 back in 2017, and we've never gone back over 2000 in over 3 years. So shouldn't our minimum LLMQ size be adjusted to meet the PIVX numbers, and not DASH's? i.e. 200 instead of 400 (for lack of better knowledge...) 

And to add to the incentive theory, we should not underestimate the incentivization of doubling the treasury for the project and how it may benefit this project and investor's perception. Also, as a supplement argument; PIVX initially had a lower MN reward amount (due to seesaw, then due to zPoS) than currently. We are only in this situation because of loss of zPoS. Not because of some well studied decision. Also, while the MN reward rate was at its lowest back in 2017, our MN count was at our highest. That obviously goes against the conservative arguments about this block reward re-distribution, and is the key reason for this RFC's existence. 

What we are trying to achieve is to increase the size of our 1st tier and 2nd tier network, through the use of the increased funds to support this project, as we know that it won't just increase by holding on to this block reward ratio.

But yeah, I'm all ears for compromises and middle grounds. I'm simply voicing my opinion based on my near 9 years of crypto market knowledge and hands-on experience in multiple projects, including PIVX.

**Comment by jakimanboy** [comment]
I have done much more research on this matter, and also have received and seen many feedbacks and concerns. So I also now do agree that 2:2:2 is a not as ideal. The fact that that kind of response is seen matters, as some MNO may also think the same way. 

Going by what was disccussed about the technical need to have higher MN count  (even more than now being preferred), and to be able to achieve that while also satisfying the project's need for more funding, I now agree that having incentivization of MN would be preferred to make sure it stays psychologically more attractive compared to PoS. Existing proposals above only affects the MN users and in a negative way. So here is my new suggestion that will satisfy all our needs and also benefit the project as a whole.

[Option 3]
MN / PoS / Treasury
2.5 / 1.5 / 2

Option 3 is very interesting as it would double our budget, while also making MN even "more" profitable compared to PoS (66% instead of 50% that it is now), and also decreases PoS reward which will further enhance the attractiveness of running a MN. Considering MN will cost more to run, and will become more invaluable, this "shift" makes sense. 

Essentially, this will achieve everything that this project needs and what the community wants without increasing the coin emission rate. (in fact, this technically reduces the block's coin emission rate by 20% compared to current)

So lets put this on the chopping board for discussion also.

**Comment by ambassador000** [comment]
It's great to hear the Option 3. It makes a lot of sense as it actually tackles all the points and concerns mentioned in this RFC.

As it was stated, with the v6.0 launch Masternodes will play much more significant role in the network, so the Option 3 still retains a significant incentive to run a Masternode compared to Staking, but a budget will be significantly higher, allowing much more room for marketing. It's safe to assume that more marketing leads to more new users/investors and higher price per PIV, which historically provenly resulted with the increased MN count. PIVX MN count did hit an all time high when the price per PIV was the highest. It's happening with other Masternode coins as well, not just PIVX.

So the Option 3 actually helps towards the expanding the Masternode network further with more Masternodes in circulation. 

It makes sense also because PIVX's supply is already 100% distributed and it's hard to get any bigger funding unless it's coming by community donations. We all know that community isn't donating much which is the issue. One of the possible explanations why donations aren't happening is because PIVX is an old coin and a lot of coin supply is being lost/forgotten forever. If so, that cannot be fixed, but the treasury can be increased as a possible solution.

Lack of funding due to "perfect coin economics" explains why PIVX isn't doing so well price-wise compared to very inflationary coins that are able to throw away a lot of coins on marketing, giveaways, influencers, funding liquidity mining, trading competitions, etc. 

Sorry about a small off-topic in the last 2 paragraphs, but wanted to make it public to stay here for future discussions.

**Comment by EricStanek** [comment]
**Some questions:**

1. Are the devs in agreement with Option 3? (2.5 MNs / 1.5 Stakers / 2.0 Treasury)
2. Can it be implemented with v6.0 protocol bump?
3. Will it be controlled by a Spork so we can make the change when ready?

**Comment by panleone** [comment]
Reward distribution has been updated with v5.5 this issue can be closed
