### ISSUE TITLE
[Bug][GUI] "Select/Unselect All" button acts very weird on coin control slections

### ISSUE THREAD

**Issue by kyeno** [PIVX-Project/PIVX#2689]
When you go to "Send" tab, then use "Coin Control" and f.e., decide to gather some masternode rewards, the "Unselect All" button becomes enabled out of nowhere. From my testing - after 69 PIVs are selected or 23 inputs clicked.

Applies ever since I can remember (4.x, 5.x), just didn't have time to report it before.
Reproducable both on Linux and Mac builds.

![Record_select-area_20211216215440](https://user-images.githubusercontent.com/1790957/146448522-82253d9c-88bc-4558-bad1-6db124ab3b89.gif)

**Comment by kyeno** [comment]
Also it seems the "gap" between the checkbox and the value is also selectable and looks a bit like text input.

**Comment by furszy** [comment]
Tell me the truth, you made the video only to show the background :)

**Comment by kyeno** [comment]
> Tell me the truth, you made the video only to show the background :)

Haha, actually no! :)
My screen recorder for some reason did not allow me to "shrink" the width of the recording area of this height, and I didn't want to dox any of the information on the right - since this isn't testnet wallet. ;)

**Comment by EricStanek** [comment]
I am guessing that it is by design. The 'Unselect All" button appeared once I had selected over 50% of the rows. Thus, the un-select becomes more efficient when you include its functionality in concert with the 'Toggle lock state' button immediately beside it.

![_unselect_13](https://user-images.githubusercontent.com/24375948/146464518-5499a2b2-7f2d-4c9f-91de-f2ef1ffc6f36.png)

**Comment by EricStanek** [comment]
I rarely use it, but the 'Lock Unspent' function in the past showed a 'lock' icon. Now I don't see it ... just a shaded area. Could be that I have an edge case, because my screen display settings are scaled/set for poor eyesight.

Regardless, the 'Toggle lock state' is acting like it is 'Unlock all'.

https://user-images.githubusercontent.com/24375948/146466180-555b4697-c958-4169-a7ab-4ddfd59e2c73.mp4

**Comment by Fuzzbawls** [comment]
> I am guessing that it is by design. The 'Unselect All" button appeared once I had selected over 50% of the rows. Thus, the un-select becomes more efficient when you include its functionality in concert with the 'Toggle lock state' button immediately beside it.

This is correct
```cpp
// update SelectAll button state
// if inputs selected > inputs unselected, set checked (label "Unselect All")
// if inputs selected <= inputs unselected, set unchecked (label "Select All")
updatePushButtonSelectAll(coinControl->QuantitySelected() * 2 > nSelectableInputs);
```

> I rarely use it, but the 'Lock Unspent' function in the past showed a 'lock' icon. Now I don't see it ... just a shaded area. Could be that I have an edge case, because my screen display settings are scaled/set for poor eyesight.
> 
> Regardless, the 'Toggle lock state' is acting like it is 'Unlock all'.

Looks like you're in the shield coin control UI (Received with column addresses starting with `ps1`), which has never supported locking/unlocking, and the context menu options, as well as the button at the top have been removed for the 5.4.0 release in #2662

**Comment by random-zebra** [comment]
> > I am guessing that it is by design. 
> 
> This is correct

Yep (since v4.2). From the discussion in #1612.
Closing

**Comment by kyeno** [comment]
That is the least user-friendly "expected behavior" one could expect. ;)

**Comment by random-zebra** [comment]
It was a feature specifically requested (that's why I linked the PR) and it seemed a valid compromise.
But feel free to suggest something different, if you think it can improve the usability, and we can discuss it together.

I closed this ticket because it's not a bug and the button does not "act very weird", it works as designed.

**Comment by kyeno** [comment]
Okay, I hear you. I'll suggest a different behavior then within a couple days then.
