### ISSUE TITLE
Language Translations

### ISSUE THREAD

**Issue by skironDotNet** [PIVX-Project/PIVX#2754]
I'm very disappointed with how PIVX is handling the translations. The idea is to use Tansifex, but it's not as easy as just adding of edits, you need to become organization member, but existing language **Polish 98.3%** is not on the list. So I was trying to outsmart the system and requested "Slovak" and my request got rejected. So how the hell this is useful approach? People want to participate for free and they can't. Would be better to let people to just submit translations via GIT

![image](https://user-images.githubusercontent.com/2981715/156897289-3112464e-f856-49ea-b0b5-7bbf559318d3.png)

![image](https://user-images.githubusercontent.com/2981715/156897350-5b5831a2-bb21-48cd-8426-26d4ba349993.png)

**Comment by Fuzzbawls** [comment]
`Polish` is a pre-existing language in our Transifex project (see below screenshot). Your request to add a new language of `Polish (Poland)` would have been a redundant addition, which is why it was rejected.

I will say that Transifex does have a shortcoming in the way requests and notifications are displayed to project admins/maintainers. New language requests are shown on every page as a notification in your profile avatar, however team join requests are only shown on the teams page. I've accepted your request to join the team for the existing languages, and will submit a ticket to Transifex to inquire as to why team join requests aren't properly being shown as global notifications.
![Image 114](https://user-images.githubusercontent.com/7393257/156903504-19a32dfd-b391-4da0-af0b-d16f54c58d76.png)

**Comment by skironDotNet** [comment]
Thanks for quick reply on this. I think if possible would be nice to delete `Polish (Poland)` as this may be some super old. If I requested that it was probably part of me trying to outsmart the system because `Polish` was not in the dropdown as seen on my first picture.

Thank you.
