### ISSUE TITLE
Money supply diffrence?

### ISSUE THREAD

**Issue by skironDotNet** [PIVX-Project/PIVX#2797]
I ran a few nodes, but comparing result of the 2 hosted from different VPS makes me wonder, both are same version, synced, same block hash, but different money supply? Shouldn't all node report same results?

![image](https://user-images.githubusercontent.com/2981715/215359229-9053ce19-e0ac-424c-bbc1-3f66638d64b7.png)

**Comment by skironDotNet** [comment]
I wonder if my chain is messed up related to https://github.com/PIVX-Project/PIVX/issues/2796 
I'll try to re-sync chains, and see then...

**Comment by skironDotNet** [comment]
MN produces 6piv every 1 min, so how come QT client is reporting same supply a few blocks later?
![image](https://user-images.githubusercontent.com/2981715/215362599-2f60c73c-fc49-4256-8cf6-186a11341848.png)

**Comment by skironDotNet** [comment]
Ok so money supply is calculated only once during pivx start and then never updates during process live cycle, stopping ans starting pivx will give new value then. **I think it's a bug, and getinfo should report real-time value**s

**Comment by Liquid369** [comment]
Thanks for the information, technically this is by design. 
```getinfo``` rpc with the way Money Supply calculation was changed was becoming clunky and slow, so it was changed in this PR https://github.com/PIVX-Project/PIVX/pull/1906
That introduced a new RPC called ```getsupplyinfo``` that will trigger an update on the money supply cache/calculation for you. 
There are 3 cases in which the update is trigger for Money Supply
- at startup
- after periodic full flushes to disk (blocks and chainstate), except during shutdown or IBD
- on-demand via RPC (getsupplyinfo)

**Comment by Fuzzbawls** [comment]
`getinfo` is a partially deprecated RPC command. As @Liquid369 points out, there is `getsupplyinfo`, which is much more accurate and can be forced to update on-demand.

This change was documented in the v5.0.0 release notes <https://github.com/PIVX-Project/PIVX/blob/master/doc/release-notes/release-notes-5.0.0.md#rpc-changes> first published on Jan 8, 2021 <https://github.com/PIVX-Project/PIVX/releases/tag/v5.0.0>

**Comment by skironDotNet** [comment]
Works as designed
