### ISSUE TITLE
Loading shielded blocks never finished. 

### ISSUE THREAD

**Issue by Usmanahmed7090** [PIVX-Project/PIVX#2938]
Discord help is not helpful. I do everything that they told me to do but nothing work and loading shielded blocks never finished and stuck on "app.mypivxwallet.org" . I can't access my wallet since more than 3 months. Please guide me something that will solve my problem.

**Comment by Darrenpeaker** [comment]
> Discord help is not helpful. I do everything that they told me to do but nothing work and loading shielded blocks never finished and stuck on "app.mypivxwallet.org" . I can't access my wallet since more than 3 months. Please guide me something that will solve my problem.

@Usmanahmed7090 It seems like you're encountering difficulties with loading shielded blocks and accessing your wallet on "app.mypivxwallet.org" via Discord help. Since you've tried the steps they provided without success,it sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID PIV07638
Please see the link below to our dedicated support line:
[PIVX Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Fuzzbawls** [comment]
This repository is for the PIVX Core wallet. Issues with MPW should be filed at https://github.com/PIVX-Labs/MyPIVXWallet
