### ISSUE TITLE
Getting "Unknown proposal name" error message on rpc call "getbudgetinfo core-dev-fuel+2"

### ISSUE THREAD

**Issue by openbaringen** [PIVX-Project/PIVX#398]
Hi, 

I'm getting "Unknown proposal name" error message on rpc call `getbudgetinfo core-dev-fuel+2`. The proposal however exists and when I call `getbudgetprojection` it returns the proposal name as "core-dev-fuel+2". When the "2" is removed the data is returned. Most probable a parsing issue with the '+' sign. The same occurs for `getbudgetvotes`

Steps to reproduce
1. start `pivxd` with `pivxd -rpcpassword=<password> -rpcuser=<username> -server=1` 
2. wait for the chain to sync
3. call `pivx-cli -rpcpassword=<password> -rpcuser=<username> getbudgetinfo core-dev-fuel+2`

Core version = 3.0.5
OS= fedora 26

**Comment by Fuzzbawls** [comment]
Known issue due to a change in string sanitization for proposal names. The issue will resolve itself going forward, but unfortunately cannot be "fixed" for the proposal in question.

This is caused by the `+` character in the proposal name, which has since been disallowed, and won't be accepted in any future proposal name.
