### ISSUE TITLE
Failed reading from database. pcoinsTip best block is not correct. The block database is in an inconsistent state and may cause issues in the future.To force start use -forcestart

### ISSUE THREAD

**Issue by AxelOrm** [PIVX-Project/PIVX#407]
I consistently get the message in the topic line when I try to open the wallet. 

I have no idea how to force start.

Help would be much appreciated.
![pivx01](https://user-images.githubusercontent.com/33915125/33154603-4d4002aa-cf9e-11e7-9691-25ef5b3770ff.PNG)
![pivx02](https://user-images.githubusercontent.com/33915125/33154604-4d57f9fa-cf9e-11e7-8682-de8400c38fdb.PNG)
![pivx03](https://user-images.githubusercontent.com/33915125/33154605-4d6edefe-cf9e-11e7-875a-84f33ced0500.PNG)

**Comment by presstab** [comment]
#405 should fix this issue.

**Comment by faisalharianawalla** [comment]
Did you find out how to resolve this issue ? I am having the same error !! If anyone can please let me know what to do to resolve this isse it will be much appreciated!!

**Comment by AxelOrm** [comment]
Hey presstab. I really appreciate your effort here. However, to a non-programmer like myself, the #405 thread is incomprehensible. Not sure what to do from here.

**Comment by mycoins** [comment]
I am getting the same message, did we get a fix?

**Comment by faisalharianawalla** [comment]
On the official PIVX website it says to erase files and to reset the system. I have done that but it is still trying to resychronize with the network. I don't know if it working because it has been almost 2-3 days but still shows 0% with 1 year and 42 weeks remaining. Let me know and I can guide you to the place on the website that gives the instructions if you would like to try that fix....
Thanks !

**Comment by Warrows** [comment]
Isn't this issue fixed in latest versions ?

**Comment by mycoins** [comment]
Yep Yep it is fixed
