### ISSUE TITLE
precompiled pivx-qt is trying to access /home/ubuntu

### ISSUE THREAD

**Issue by baryluk** [PIVX-Project/PIVX#637]
`pivx-3.1.0`

`firejail --build ./pivx-qt  `:
```
4:pivx-qt:exec /home/baryluk/Linux/pivx/pivx-3.1.0/bin/pivx-qt:0
4:pivx-qt:open /dev/urandom:3
4:pivx-qt:open64 /dev/urandom:3
4:pivx-qt:open64 /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/qtlogging.ini:-1
4:pivx-qt:socket AF_LOCAL SOCK_STREAM 0:3
4:pivx-qt:connect 3 @/tmp/.X11-unix/X0:0
4:pivx-qt:access /home/baryluk/.Xauthority:0
4:pivx-qt:fopen /home/baryluk/.Xauthority:0x2abd320
4:pivx-qt:open64 /home/baryluk/.config/PIVX/PIVX-Qt.conf:6
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt_pl.qm:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt_pl:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt.qm:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt_pl_PL.qm:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt_pl_PL:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt_pl.qm:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt_pl:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt.qm:-1
4:pivx-qt:access /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/translations/qt:-1
...
```

Please stop.

Some hardcoded paths in binary:
`strings pivx-tx | grep ubuntu` :
```
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/smart_ptr/scoped_ptr.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/smart_ptr/shared_ptr.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/optional/optional.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/signals2/detail/auto_buffer.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/signals2/detail/lwm_pthreads.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/thread/pthread/mutex.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/thread/pthread/recursive_mutex.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/signals2/connection.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/variant/detail/forced_return.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/signals2/detail/slot_groups.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/signals2/detail/signal_template.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/unordered/detail/implementation.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/exception/detail/exception_ptr.hpp
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/lib/engines
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/etc/openssl/private
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/etc/openssl
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/etc/openssl/certs
/home/ubuntu/build/pivx/depends/x86_64-linux-gnu/etc/openssl/cert.pem
GCC: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
GCC: (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

but granted some of these might be just part of debug symbol tables. Which is unlikely because:

`file pivx-qt` :
```
pivx-qt: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=e009eb38b471b708a70ac551430c6121a46a215e, stripped
```

**Comment by EvertonMelo** [comment]
@baryluk 

Did you ever run build check? 

please verify:

Build Variables:

After defining the main identifiers, build variables may be added or customized before running the build commands. They should be added to a function called $(package)_set_vars. For example:

define $(package)_set_vars
...
endef

Most variables can be prefixed with the host, architecture, or both, to make the modifications specific to that case. For example:

Universal:     $(package)_cc=gcc
Linux only:    $(package)_linux_cc=gcc
x86_64 only:       $(package)_x86_64_cc = gcc
x86_64 linux only: $(package)_x86_64_linux_cc = gcc

These variables may be set to override or append their default values.

$(package)_cc
$(package)_cxx
$(package)_objc
$(package)_objcxx
$(package)_ar
$(package)_ranlib
$(package)_libtool
$(package)_nm
$(package)_cflags
$(package)_cxxflags
$(package)_ldflags
$(package)_cppflags
$(package)_config_env
$(package)_build_env
$(package)_stage_env
$(package)_build_opts
$(package)_config_opts

The *_env variables are used to add environment variables to the respective commands.

Many variables respect a debug/release suffix as well, in order to use them for only the appropriate build config. For example:

$(package)_cflags_release = -O3
$(package)_cflags_i686_debug = -g
$(package)_config_opts_release = --disable-debug

These will be used in addition to the options that do not specify debug/release. All builds are considered to be release unless DEBUG=1 is set by the user. Other variables may be defined as needed.


https://github.com/PIVX-Project/PIVX/blob/master/depends/packages.md

**Comment by baryluk** [comment]
I used your precompiled binaries from the website!

**Comment by ScaMar** [comment]
I don't get the point. That gitian builds are not made following the art of perfection? If you want a binary without extra strings in it, build it yourself, my CPU isn't hurt for loosing few ms to search not found file before getting the call (that is statistically added in)

**Comment by baryluk** [comment]
@ScaMar It is not about "extra" strings.

The binary is in fact accessing files that it should not be accessing.

Out of thousands of programs on my system, pivx-qt is only one doing this, polluting my audit logs, possibly accessing network file systems, etc.

**Comment by baryluk** [comment]
@random-zebra This is still not fixed.

I verified it is still a problem with pivx-qt 4.0.0
