### ISSUE TITLE
[UX] Orphan block presentation

### ISSUE THREAD

**Issue by PIVXStrontium** [PIVX-Project/PIVX#674]
### Describe the issue
The presentation of orphan block has caused a lot of negativity within the PIVX community. I believe loss aversion (https://en.wikipedia.org/wiki/Loss_aversion) to be at the heart of this. While I strongly believe a default state of hiding rewards until confirmed with the option to show immediately is ideal, as an easy means of managing the problem now, I believe the colour presentation of the orphan block rewards and successful staking rewards should be altered for a more positive psychological impact.

### Change details
- Standard transactions remain printed in black, as now
- Rewards are now printed in purple, from black
- When orphaned, rewards are greyed out, from red

This does not solve the 'loss aversion' problem, but it heightens the impact of successful rewards, and lessens the negative impact of seeing an orphaned block (grey is much less aggravating or blame-placing than red psychologically, and implies invalidity/non-applicability rather than user error).

### Screenshots.
![image](https://user-images.githubusercontent.com/38264865/43351871-fda0cdfa-9253-11e8-8106-3dc8732faa7d.png)
Top current. Bottom proposed.

**Comment by mhannigan** [comment]
Is there really a need for the average user to see orphaned blocks?

I completely agree with the concept of avoiding "loss aversion" - it's a profoundly negative emotion.  I think the "loss aversion" could best be achieved by not displaying orphans in the default view. Waiting for 1 or 2 confirmations to display them would be ideal since orphans are almost always declared before the first confirmation.

**Comment by PIVXStrontium** [comment]
mhannigan devs have determined that they feel the showing of orphan blocks should remain. I personally agree with what you're saying as the original comment shows, but at the end of the day that's a dev decision to make.

**Comment by turnkit** [comment]
I totally agree with the need to hide orphan blocks.  I am so annoyed that I am costly "losing" rewards I am becoming paranoid that zPIV staking is completely broken and someone is "stealing" everyone's rewards most of the time... and all due to the poor rewards of zPIV.  In fact partly because of all the negative orphaned block notices I returned all my zPIV to PIV so that I, supposing, can get a better return. Would really like to see some stat showing "average % of time staking" and average % rewarded during staked time, expected and actual for 1 day, 7 days, 30 days, 90 days, etc. when available.  Right now partly because of the constant negative orphaned reports I have lost emotional confidence that staking is working.  I have no idea if this is actually true or not and because I have no hard facts to back up a claim either way I just rely on gut, which is being influenced by a constant reminder that I am losing out my staking rewards to someone else, someone who won the reward for being "faster" while mine reward was taken, being orphaned, for some mysterious reason.  Not a nice experience at all.
