### ISSUE TITLE
[UX][UI] Masternode tab - information for new users

### ISSUE THREAD

**Issue by StrontiumZ38** [PIVX-Project/PIVX#689]
### Describe the issue
Currently, the Masternode tab provides new users with no information on what a masternode is or how to set one up. It assumes the user is already fully aware of this information, and provides no way for the user to learn about Masternodes outside of googling for answers.

### Suggested solution
Add a button to the top of the Masternode tab that opens a pop-up window (like the About window) with a brief explanation of masternodes, requirements, and a suggestion to head to the PIVX website to learn more.

**A example of what the window might state:**
_Masternodes are a set of incentivised nodes on a second tier within the PIVX network. Involved in specialised tasks such as SwiftX transactions and voting on budget proposals, masternodes are an integral part of the PIVX digital ecosystem, and necessary to network functionality.
Masternodes are incentivised, paying out PIV to the operator in return for their service. If a user holds 10,000 PIV or more, they are eligible to host a masternode. For further information and detailed instructions on creating a masternode, visit the PIVX official website._

This could always be trimmed if deemed too lengthy.

### Screenshots.
![image](https://user-images.githubusercontent.com/38264865/43691402-e3a1da2a-9956-11e8-80f2-8d65bd278cca.png)
Masternode tab with about the button.

**Comment by Fuzzbawls** [comment]
Given the current work load of the dev team, I am more inclined to NACK this kind of change; This information is readily available elsewhere (with translations), and adding it to the wallet would be completely dependent on the translation team actually following through.

**Comment by PIVXStrontium** [comment]
I had that intention at first Warrows, but zebra mentioned it may present a security risk? This was the next solution to come to mind.

**Comment by Carbon-Zero** [comment]
It seems unnecessary considering sources available for this kind of information. It would be better to place this in documentation or a tutorial somewhere. If this is added, where do you draw the line in terms of linking to external pages to educate? Unnecessary addition to code.

**Comment by XxTheMatrix101xX** [comment]
I would rather not have information on the masternodes tab unless you already had a valid masternode. people seem to think they dont need to worry about masternodes and they arent "real" nodes and thus dont need to check on them for months at a time. i would make troubleshooting info very easy to anyone who asks/needs it (e.g. a button in the wallet brings up troubleshooting pages) but the creation pages and a simple walkthrough....nope
and just so you know where im coming from, i thought the same thing, make it easier to have a masternode and we will get more masternode owners. I made a script that does everything needed to set up a masternode and all it needs is the collateral address and it does everything else. downloads dependencies, compile the wallet, checks the chain sync state, checks the masternode address for collateral, selects collateral, updates the configs, and then copies the masternode.conf to your clipboard so you can put it in your wallet. I made this and just when i was about to release it people started complaining that their masternode had gone off on a fork and they werent being paid. i walked them through fixing it and asked them what block they forked on and it had literally been almost 9 months since they had gone off on a fork and the guy never checked anything. because he thought masternodes were so easy and they just worked with no work involved.

**Comment by random-zebra** [comment]
fixed in #954
