### ISSUE TITLE
zero fee transactions from without GUI

### ISSUE THREAD

**Issue by rocket-pig** [PIVX-Project/PIVX#796]
### Describe the issue
`settxfee 0` changes appearance of fee in other RPC responses but has no effect.  Fee is still used, seems non-adjustable whatsoever.

Can same functionality used in qt gui with the "set zero-fee transaction" checkbox be also accessible via cli?

**Comment by rocket-pig** [comment]
I downloaded source and found this in rpcwallet.cpp: line 2110
```
    // Amount
    CAmount nAmount = 0;
    if (params[0].get_real() != 0.0)
        nAmount = AmountFromValue(params[0]); // rejects 0.0 amounts

    payTxFee = CFeeRate(nAmount, 1000);
    return true;
}


```
so yeah. Basically its set to prevent zero fee transactions from command line. Which IMO sucks - we have an underutilized mainly completely empty mempool....why not tout free transactions as a way of drawing new folks?  Since its been 16 days with no response I'll assume nobody's willing to talk about this and just leave this here for the next person that thinks wtf

**Comment by furszy** [comment]
Free transactions are not a realistic possibility, could enable a huge attack vector. Blockchain storage is forever.
Without blockchain fee, with only few coins you or anyone could spam the network relatively easy.

Saying that, there is an available space for zero fee txes in each block. It's usable: yes, is the core wallet a good place to have it: not really.

**Comment by rocket-pig** [comment]
There's a number of methods in use, on which none of am I knowledgeable, to prevent spamming on zero-fee networks.  Its not only a 'realistic possibility' but already done on a number of other networks in a number of different ways. I couldnt elaborate because I havent studied them, but to say its 'unrealistic' when its already in practice elsewhere is... 'unrealistic'

**Comment by Carbon-Zero** [comment]
There are already a sufficient number of checks for abuse of 0-fee transactions.

**Comment by Warrows** [comment]
This particular part of the code is not responsible for anything. The comment can be misleading because in fact `AmountFromValue` would refuse to set a value of zero and return an error. But given that `nAmount` is initialized at 0, if the provided value is zero then that is the value of `payTxFee` at the end. As you can see by running the rpc command `getwalletinfo` after.

And in fact the wallet will normally process the transaction. For example, if you use `sendtoaddress` after setting the fee to zero, it will decide if the fee can actually be zero or not, based on the mempool and the size of the tx. It will then send it with the appropriate fee which can be zero but can be more. Exactly the same as what is happening in the GUI. So you can't say that 
> no-fee sends are blocked from command line.

However you are right that 

>  The code should most certainly not allow you to set fees to zero, and then charge fees anyway when you send

So that's where there is space for improvement. But I think a simple message saying that "0 fees are not always possible and the wallet will do its best to achieve it" is the way to go here.

**Comment by Carbon-Zero** [comment]
Solution suggested in PR #848
