### ISSUE TITLE
[Staking] debug.log file growth while staking

### ISSUE THREAD

**Issue by CryptoDJ** [PIVX-Project/PIVX#81]
While the wallet is staking, the debug.log file grows so fast, I run out of space in 12 hours.  In 30 minutes, it grew to 2.4 GB.  This is repeated over and over:

> 2017-03-25 07:34:59 ERROR: CheckProofOfWork() : hash doesn't match nBits
> 2017-03-25 07:34:59 ERROR: CheckBlockHeader() : proof of work failed
> 2017-03-25 07:34:59 ERROR: CheckBlock() : CheckBlockHeader failed

![debug.log](http://i.imgur.com/gC32Rtz.png)

This is my pivx.conf file:
```
rpcuser=<username>
rpcpassword=<password>
rpcallowip=127.0.0.1
server=1
listen=1
testnet=0
rpcallow=1
daemon=1
gen=1
stake=1
staking=1
debug=0
addnode=coin-server.com
```

Running PIVX on Ubuntu 16.04

**Comment by Fuzzbawls** [comment]
lots of useless entries in your conf file, and `gen=1` is your worst offender. PoW is long since over so you should not be trying to generate any PoW blocks (that is what this line is telling your wallet to do)

Here is a fixed conf file sample based on what you provided:

```
rpcuser=<username>
rpcpassword=<password>
rpcallowip=127.0.0.1
server=1
listen=1
daemon=1
staking=1
```

Everything that I left out is either un-necessary, or downright incorrect.

**Comment by CryptoDJ** [comment]
https://github.com/PIVX-Project/PIVX/pull/83 removes the gen command that was causing the bloated debug.log file.

**Comment by CryptoDJ** [comment]
gen=1 was the cause.  Closing this issue.  thank you.
