### ISSUE TITLE
Is www.electrumpivx.org ok to use for multisig?

### ISSUE THREAD

**Issue by alesito85** [PIVX-Project/PIVX#893]
The goal is to not have to have the whole chain synced. So is it ok to use or not?

**Comment by edykstra** [comment]
That site is a scam. They will steal your coins.

**Comment by alesito85** [comment]
Thanks. Any source for that?

**Comment by EricStanek** [comment]
I agree. Site is a scam. There are MANY warning signs.

1. It is not 'official' at all. If it was, the binaries would be signed and on the PIVX Github.
2. You will not find a single respected person in the PIVX Community suggesting you use this wallet.
3. They imply source is available by linking to a proper PIVX Core wallet. That is not an Electrum wallet.
4. They use Pivx all over the place instead of PIVX.
5. They state that PIVX supports Segwit. It does not.
6. They fail to mention there is are PIVX iOS and Android wallets, but list 3rd parties.
7. The wording plays on the 'Fear of failure' emotion.
8. They state; "...to send all the Pivxs ...". No one in PIVX says 'Pivxs'. They say PIV.
9. There is no 'Contact Us' information. Not that you could trust it anyways.
10. The site does not have a SSL certificate.

Join the PIVX Discord and ask around. You will be flooded with 'Stay Away' comments.
